// Code generated by clients_gen. DO NOT EDIT.

package config

import (
	"context"
	"fmt"

	"google.golang.org/grpc"

	kingsguardclientPkg "github.com/CodefriendOrg/tirion/internal/pb/github.com/CodefriendOrg/kingsguard/pkg/kingsguard"
)

type GrpcClientsContainer struct {
	kingsguardclient kingsguardclientPkg.KingsguardClient
}

func NewGrpcClientsContainer(ctx context.Context) (*GrpcClientsContainer, error) {
	s := &GrpcClientsContainer{}
	var serviceUrl string
	var err error
	var conn grpc.ClientConnInterface

	serviceUrl = "codefriend-kingsguard-zsqd1w:50051"
	conn, err = dialContainerService(ctx, serviceUrl, "3s")
	if err != nil {
		return nil, fmt.Errorf("dialContainerService for service %s failed %w", serviceUrl, err)
	}
	s.kingsguardclient = kingsguardclientPkg.NewKingsguardClient(conn)

	return s, nil
}

func (s *GrpcClientsContainer) GetKingsguardclient() kingsguardclientPkg.KingsguardClient {
	return s.kingsguardclient
}
