// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: vendor.protogen/gitlab.codefriend.ru/backend/kingsguard/kingsguard.proto

package kingsguard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiredAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateTokenResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto protoreflect.FileDescriptor

const file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDesc = "" +
	"\n" +
	"Hvendor.protogen/gitlab.codefriend.ru/backend/kingsguard/kingsguard.proto\x12\n" +
	"kingsguard\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x129\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"8\n" +
	"\x10RegisterResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.kingsguard.UserR\x04user\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"m\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x129\n" +
	"\n" +
	"expired_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\"9\n" +
	"\x14ValidateTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"=\n" +
	"\x15ValidateTokenResponse\x12$\n" +
	"\x04user\x18\x02 \x01(\v2\x10.kingsguard.UserR\x04user\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"7\n" +
	"\x0fGetUserResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.kingsguard.UserR\x04user2\xab\x02\n" +
	"\n" +
	"Kingsguard\x12E\n" +
	"\bRegister\x12\x1b.kingsguard.RegisterRequest\x1a\x1c.kingsguard.RegisterResponse\x12<\n" +
	"\x05Login\x12\x18.kingsguard.LoginRequest\x1a\x19.kingsguard.LoginResponse\x12T\n" +
	"\rValidateToken\x12 .kingsguard.ValidateTokenRequest\x1a!.kingsguard.ValidateTokenResponse\x12B\n" +
	"\aGetUser\x12\x1a.kingsguard.GetUserRequest\x1a\x1b.kingsguard.GetUserResponseB?Z=github.com/CodefriendOrg/kingsguard/pkg/kingsguard;kingsguardb\x06proto3"

var (
	file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDescOnce sync.Once
	file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDescData []byte
)

func file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDescGZIP() []byte {
	file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDescOnce.Do(func() {
		file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDesc), len(file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDesc)))
	})
	return file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDescData
}

var file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_goTypes = []any{
	(*User)(nil),                  // 0: kingsguard.User
	(*RegisterRequest)(nil),       // 1: kingsguard.RegisterRequest
	(*RegisterResponse)(nil),      // 2: kingsguard.RegisterResponse
	(*LoginRequest)(nil),          // 3: kingsguard.LoginRequest
	(*LoginResponse)(nil),         // 4: kingsguard.LoginResponse
	(*ValidateTokenRequest)(nil),  // 5: kingsguard.ValidateTokenRequest
	(*ValidateTokenResponse)(nil), // 6: kingsguard.ValidateTokenResponse
	(*GetUserRequest)(nil),        // 7: kingsguard.GetUserRequest
	(*GetUserResponse)(nil),       // 8: kingsguard.GetUserResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_depIdxs = []int32{
	9,  // 0: kingsguard.User.deleted_at:type_name -> google.protobuf.Timestamp
	9,  // 1: kingsguard.User.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 2: kingsguard.User.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: kingsguard.RegisterResponse.user:type_name -> kingsguard.User
	9,  // 4: kingsguard.LoginResponse.expired_at:type_name -> google.protobuf.Timestamp
	0,  // 5: kingsguard.ValidateTokenResponse.user:type_name -> kingsguard.User
	0,  // 6: kingsguard.GetUserResponse.user:type_name -> kingsguard.User
	1,  // 7: kingsguard.Kingsguard.Register:input_type -> kingsguard.RegisterRequest
	3,  // 8: kingsguard.Kingsguard.Login:input_type -> kingsguard.LoginRequest
	5,  // 9: kingsguard.Kingsguard.ValidateToken:input_type -> kingsguard.ValidateTokenRequest
	7,  // 10: kingsguard.Kingsguard.GetUser:input_type -> kingsguard.GetUserRequest
	2,  // 11: kingsguard.Kingsguard.Register:output_type -> kingsguard.RegisterResponse
	4,  // 12: kingsguard.Kingsguard.Login:output_type -> kingsguard.LoginResponse
	6,  // 13: kingsguard.Kingsguard.ValidateToken:output_type -> kingsguard.ValidateTokenResponse
	8,  // 14: kingsguard.Kingsguard.GetUser:output_type -> kingsguard.GetUserResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_init() }
func file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_init() {
	if File_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDesc), len(file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_goTypes,
		DependencyIndexes: file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_depIdxs,
		MessageInfos:      file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_msgTypes,
	}.Build()
	File_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto = out.File
	file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_goTypes = nil
	file_vendor_protogen_gitlab_codefriend_ru_backend_kingsguard_kingsguard_proto_depIdxs = nil
}
