// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/tirion.proto

package tirion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderDirection int32

const (
	OrderDirection_ASC  OrderDirection = 0
	OrderDirection_DESC OrderDirection = 1
)

// Enum value maps for OrderDirection.
var (
	OrderDirection_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	OrderDirection_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x OrderDirection) Enum() *OrderDirection {
	p := new(OrderDirection)
	*p = x
	return p
}

func (x OrderDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_api_tirion_proto_enumTypes[0].Descriptor()
}

func (OrderDirection) Type() protoreflect.EnumType {
	return &file_api_tirion_proto_enumTypes[0]
}

func (x OrderDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderDirection.Descriptor instead.
func (OrderDirection) EnumDescriptor() ([]byte, []int) {
	return file_api_tirion_proto_rawDescGZIP(), []int{0}
}

type ListProblemsRequest_OrderByField int32

const (
	ListProblemsRequest_CREATED_AT ListProblemsRequest_OrderByField = 0
)

// Enum value maps for ListProblemsRequest_OrderByField.
var (
	ListProblemsRequest_OrderByField_name = map[int32]string{
		0: "CREATED_AT",
	}
	ListProblemsRequest_OrderByField_value = map[string]int32{
		"CREATED_AT": 0,
	}
)

func (x ListProblemsRequest_OrderByField) Enum() *ListProblemsRequest_OrderByField {
	p := new(ListProblemsRequest_OrderByField)
	*p = x
	return p
}

func (x ListProblemsRequest_OrderByField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListProblemsRequest_OrderByField) Descriptor() protoreflect.EnumDescriptor {
	return file_api_tirion_proto_enumTypes[1].Descriptor()
}

func (ListProblemsRequest_OrderByField) Type() protoreflect.EnumType {
	return &file_api_tirion_proto_enumTypes[1]
}

func (x ListProblemsRequest_OrderByField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListProblemsRequest_OrderByField.Descriptor instead.
func (ListProblemsRequest_OrderByField) EnumDescriptor() ([]byte, []int) {
	return file_api_tirion_proto_rawDescGZIP(), []int{5, 0}
}

type ListTestsRequest_OrderByField int32

const (
	ListTestsRequest_CREATED_AT ListTestsRequest_OrderByField = 0
)

// Enum value maps for ListTestsRequest_OrderByField.
var (
	ListTestsRequest_OrderByField_name = map[int32]string{
		0: "CREATED_AT",
	}
	ListTestsRequest_OrderByField_value = map[string]int32{
		"CREATED_AT": 0,
	}
)

func (x ListTestsRequest_OrderByField) Enum() *ListTestsRequest_OrderByField {
	p := new(ListTestsRequest_OrderByField)
	*p = x
	return p
}

func (x ListTestsRequest_OrderByField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListTestsRequest_OrderByField) Descriptor() protoreflect.EnumDescriptor {
	return file_api_tirion_proto_enumTypes[2].Descriptor()
}

func (ListTestsRequest_OrderByField) Type() protoreflect.EnumType {
	return &file_api_tirion_proto_enumTypes[2]
}

func (x ListTestsRequest_OrderByField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListTestsRequest_OrderByField.Descriptor instead.
func (ListTestsRequest_OrderByField) EnumDescriptor() ([]byte, []int) {
	return file_api_tirion_proto_rawDescGZIP(), []int{8, 0}
}

// Задача
type Problem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Краткое описание задачи
	Summary string `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	// Описание задачи
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Время обработки ответа в миллисекундах
	TimeLimitMs int64 `protobuf:"varint,4,opt,name=time_limit_ms,json=timeLimitMs,proto3" json:"time_limit_ms,omitempty"`
	// Лимит памяти решения (user-space + куча интерпретатора), в килобайтах. В daenerys к лимиту Docker cgroup
	// добавляется настраиваемый overhead (базовый образ и рантайм), чтобы контейнер стабильно стартовал.
	MemoryLimitKb int64 `protobuf:"varint,5,opt,name=memory_limit_kb,json=memoryLimitKb,proto3" json:"memory_limit_kb,omitempty"`
	// ID автора (UUID)
	AuthorId string `protobuf:"bytes,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	// Последнее обновление задачи
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Время создания
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Problem) Reset() {
	*x = Problem{}
	mi := &file_api_tirion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problem) ProtoMessage() {}

func (x *Problem) ProtoReflect() protoreflect.Message {
	mi := &file_api_tirion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) {
	return file_api_tirion_proto_rawDescGZIP(), []int{0}
}

func (x *Problem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Problem) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Problem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Problem) GetTimeLimitMs() int64 {
	if x != nil {
		return x.TimeLimitMs
	}
	return 0
}

func (x *Problem) GetMemoryLimitKb() int64 {
	if x != nil {
		return x.MemoryLimitKb
	}
	return 0
}

func (x *Problem) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Problem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Problem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Тест к задаче
type Test struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID теста
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID задачи (UUID)
	ProblemId string `protobuf:"bytes,2,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	// Входные данные
	InputData string `protobuf:"bytes,3,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	// Ожидаемый выход
	OutputData string `protobuf:"bytes,4,opt,name=output_data,json=outputData,proto3" json:"output_data,omitempty"`
	// Скрытый тест
	IsHidden bool `protobuf:"varint,5,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	// Последнее обновление задачи
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Время создания
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test) Reset() {
	*x = Test{}
	mi := &file_api_tirion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_api_tirion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_api_tirion_proto_rawDescGZIP(), []int{1}
}

func (x *Test) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Test) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *Test) GetInputData() string {
	if x != nil {
		return x.InputData
	}
	return ""
}

func (x *Test) GetOutputData() string {
	if x != nil {
		return x.OutputData
	}
	return ""
}

func (x *Test) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

func (x *Test) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Test) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       uint64                 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_api_tirion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_api_tirion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_api_tirion_proto_rawDescGZIP(), []int{2}
}

func (x *Pagination) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPerPage() uint64 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type GetProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WithTests     bool                   `protobuf:"varint,2,opt,name=with_tests,json=withTests,proto3" json:"with_tests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProblemRequest) Reset() {
	*x = GetProblemRequest{}
	mi := &file_api_tirion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemRequest) ProtoMessage() {}

func (x *GetProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tirion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemRequest.ProtoReflect.Descriptor instead.
func (*GetProblemRequest) Descriptor() ([]byte, []int) {
	return file_api_tirion_proto_rawDescGZIP(), []int{3}
}

func (x *GetProblemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetProblemRequest) GetWithTests() bool {
	if x != nil {
		return x.WithTests
	}
	return false
}

type GetProblemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Problem       *Problem               `protobuf:"bytes,1,opt,name=problem,proto3" json:"problem,omitempty"`
	Tests         []*Test                `protobuf:"bytes,2,rep,name=tests,proto3" json:"tests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProblemResponse) Reset() {
	*x = GetProblemResponse{}
	mi := &file_api_tirion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProblemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemResponse) ProtoMessage() {}

func (x *GetProblemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tirion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemResponse.ProtoReflect.Descriptor instead.
func (*GetProblemResponse) Descriptor() ([]byte, []int) {
	return file_api_tirion_proto_rawDescGZIP(), []int{4}
}

func (x *GetProblemResponse) GetProblem() *Problem {
	if x != nil {
		return x.Problem
	}
	return nil
}

func (x *GetProblemResponse) GetTests() []*Test {
	if x != nil {
		return x.Tests
	}
	return nil
}

type ListProblemsRequest struct {
	state          protoimpl.MessageState           `protogen:"open.v1"`
	Filter         *ListProblemsRequest_Filter      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy        ListProblemsRequest_OrderByField `protobuf:"varint,2,opt,name=order_by,json=orderBy,proto3,enum=tirion.ListProblemsRequest_OrderByField" json:"order_by,omitempty"`
	OrderDirection OrderDirection                   `protobuf:"varint,3,opt,name=order_direction,json=orderDirection,proto3,enum=tirion.OrderDirection" json:"order_direction,omitempty"`
	Pagination     *Pagination                      `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListProblemsRequest) Reset() {
	*x = ListProblemsRequest{}
	mi := &file_api_tirion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProblemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProblemsRequest) ProtoMessage() {}

func (x *ListProblemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tirion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProblemsRequest.ProtoReflect.Descriptor instead.
func (*ListProblemsRequest) Descriptor() ([]byte, []int) {
	return file_api_tirion_proto_rawDescGZIP(), []int{5}
}

func (x *ListProblemsRequest) GetFilter() *ListProblemsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListProblemsRequest) GetOrderBy() ListProblemsRequest_OrderByField {
	if x != nil {
		return x.OrderBy
	}
	return ListProblemsRequest_CREATED_AT
}

func (x *ListProblemsRequest) GetOrderDirection() OrderDirection {
	if x != nil {
		return x.OrderDirection
	}
	return OrderDirection_ASC
}

func (x *ListProblemsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListProblemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Problems      []*Problem             `protobuf:"bytes,1,rep,name=problems,proto3" json:"problems,omitempty"`
	TotalItems    uint64                 `protobuf:"varint,2,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProblemsResponse) Reset() {
	*x = ListProblemsResponse{}
	mi := &file_api_tirion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProblemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProblemsResponse) ProtoMessage() {}

func (x *ListProblemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tirion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProblemsResponse.ProtoReflect.Descriptor instead.
func (*ListProblemsResponse) Descriptor() ([]byte, []int) {
	return file_api_tirion_proto_rawDescGZIP(), []int{6}
}

func (x *ListProblemsResponse) GetProblems() []*Problem {
	if x != nil {
		return x.Problems
	}
	return nil
}

func (x *ListProblemsResponse) GetTotalItems() uint64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

type CreateProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	TimeLimitMs   int64                  `protobuf:"varint,4,opt,name=time_limit_ms,json=timeLimitMs,proto3" json:"time_limit_ms,omitempty"`
	MemoryLimitKb int64                  `protobuf:"varint,5,opt,name=memory_limit_kb,json=memoryLimitKb,proto3" json:"memory_limit_kb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProblemRequest) Reset() {
	*x = CreateProblemRequest{}
	mi := &file_api_tirion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProblemRequest) ProtoMessage() {}

func (x *CreateProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tirion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProblemRequest.ProtoReflect.Descriptor instead.
func (*CreateProblemRequest) Descriptor() ([]byte, []int) {
	return file_api_tirion_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProblemRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateProblemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProblemRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CreateProblemRequest) GetTimeLimitMs() int64 {
	if x != nil {
		return x.TimeLimitMs
	}
	return 0
}

func (x *CreateProblemRequest) GetMemoryLimitKb() int64 {
	if x != nil {
		return x.MemoryLimitKb
	}
	return 0
}

type ListTestsRequest struct {
	state          protoimpl.MessageState        `protogen:"open.v1"`
	Filter         *ListTestsRequest_Filter      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy        ListTestsRequest_OrderByField `protobuf:"varint,2,opt,name=order_by,json=orderBy,proto3,enum=tirion.ListTestsRequest_OrderByField" json:"order_by,omitempty"`
	OrderDirection OrderDirection                `protobuf:"varint,3,opt,name=order_direction,json=orderDirection,proto3,enum=tirion.OrderDirection" json:"order_direction,omitempty"`
	Pagination     *Pagination                   `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTestsRequest) Reset() {
	*x = ListTestsRequest{}
	mi := &file_api_tirion_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTestsRequest) ProtoMessage() {}

func (x *ListTestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tirion_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTestsRequest.ProtoReflect.Descriptor instead.
func (*ListTestsRequest) Descriptor() ([]byte, []int) {
	return file_api_tirion_proto_rawDescGZIP(), []int{8}
}

func (x *ListTestsRequest) GetFilter() *ListTestsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListTestsRequest) GetOrderBy() ListTestsRequest_OrderByField {
	if x != nil {
		return x.OrderBy
	}
	return ListTestsRequest_CREATED_AT
}

func (x *ListTestsRequest) GetOrderDirection() OrderDirection {
	if x != nil {
		return x.OrderDirection
	}
	return OrderDirection_ASC
}

func (x *ListTestsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListTestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tests         []*Test                `protobuf:"bytes,1,rep,name=tests,proto3" json:"tests,omitempty"`
	TotalItems    uint64                 `protobuf:"varint,2,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTestsResponse) Reset() {
	*x = ListTestsResponse{}
	mi := &file_api_tirion_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTestsResponse) ProtoMessage() {}

func (x *ListTestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tirion_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTestsResponse.ProtoReflect.Descriptor instead.
func (*ListTestsResponse) Descriptor() ([]byte, []int) {
	return file_api_tirion_proto_rawDescGZIP(), []int{9}
}

func (x *ListTestsResponse) GetTests() []*Test {
	if x != nil {
		return x.Tests
	}
	return nil
}

func (x *ListTestsResponse) GetTotalItems() uint64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

type ListProblemsRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdIn          []string               `protobuf:"bytes,1,rep,name=id_in,json=idIn,proto3" json:"id_in,omitempty"`
	AuthorIdEq    *string                `protobuf:"bytes,2,opt,name=author_id_eq,json=authorIdEq,proto3,oneof" json:"author_id_eq,omitempty"`
	CreatedAtLte  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at_lte,json=createdAtLte,proto3" json:"created_at_lte,omitempty"`
	CreatedAtGte  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at_gte,json=createdAtGte,proto3" json:"created_at_gte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProblemsRequest_Filter) Reset() {
	*x = ListProblemsRequest_Filter{}
	mi := &file_api_tirion_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProblemsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProblemsRequest_Filter) ProtoMessage() {}

func (x *ListProblemsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_api_tirion_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProblemsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListProblemsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_api_tirion_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListProblemsRequest_Filter) GetIdIn() []string {
	if x != nil {
		return x.IdIn
	}
	return nil
}

func (x *ListProblemsRequest_Filter) GetAuthorIdEq() string {
	if x != nil && x.AuthorIdEq != nil {
		return *x.AuthorIdEq
	}
	return ""
}

func (x *ListProblemsRequest_Filter) GetCreatedAtLte() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtLte
	}
	return nil
}

func (x *ListProblemsRequest_Filter) GetCreatedAtGte() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtGte
	}
	return nil
}

type ListTestsRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemIdEq   string                 `protobuf:"bytes,1,opt,name=problem_id_eq,json=problemIdEq,proto3" json:"problem_id_eq,omitempty"`
	WithHidden    bool                   `protobuf:"varint,2,opt,name=with_hidden,json=withHidden,proto3" json:"with_hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTestsRequest_Filter) Reset() {
	*x = ListTestsRequest_Filter{}
	mi := &file_api_tirion_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTestsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTestsRequest_Filter) ProtoMessage() {}

func (x *ListTestsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_api_tirion_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTestsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListTestsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_api_tirion_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ListTestsRequest_Filter) GetProblemIdEq() string {
	if x != nil {
		return x.ProblemIdEq
	}
	return ""
}

func (x *ListTestsRequest_Filter) GetWithHidden() bool {
	if x != nil {
		return x.WithHidden
	}
	return false
}

var File_api_tirion_proto protoreflect.FileDescriptor

const file_api_tirion_proto_rawDesc = "" +
	"\n" +
	"\x10api/tirion.proto\x12\x06tirion\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x02\n" +
	"\aProblem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\rtime_limit_ms\x18\x04 \x01(\x03R\vtimeLimitMs\x12&\n" +
	"\x0fmemory_limit_kb\x18\x05 \x01(\x03R\rmemoryLimitKb\x12\x1b\n" +
	"\tauthor_id\x18\x06 \x01(\tR\bauthorId\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x88\x02\n" +
	"\x04Test\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x02 \x01(\tR\tproblemId\x12\x1d\n" +
	"\n" +
	"input_data\x18\x03 \x01(\tR\tinputData\x12\x1f\n" +
	"\voutput_data\x18\x04 \x01(\tR\n" +
	"outputData\x12\x1b\n" +
	"\tis_hidden\x18\x05 \x01(\bR\bisHidden\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\";\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x04R\aperPage\"B\n" +
	"\x11GetProblemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"with_tests\x18\x02 \x01(\bR\twithTests\"c\n" +
	"\x12GetProblemResponse\x12)\n" +
	"\aproblem\x18\x01 \x01(\v2\x0f.tirion.ProblemR\aproblem\x12\"\n" +
	"\x05tests\x18\x02 \x03(\v2\f.tirion.TestR\x05tests\"\x87\x04\n" +
	"\x13ListProblemsRequest\x12:\n" +
	"\x06filter\x18\x01 \x01(\v2\".tirion.ListProblemsRequest.FilterR\x06filter\x12C\n" +
	"\border_by\x18\x02 \x01(\x0e2(.tirion.ListProblemsRequest.OrderByFieldR\aorderBy\x12?\n" +
	"\x0forder_direction\x18\x03 \x01(\x0e2\x16.tirion.OrderDirectionR\x0eorderDirection\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.tirion.PaginationR\n" +
	"pagination\x1a\xd9\x01\n" +
	"\x06Filter\x12\x13\n" +
	"\x05id_in\x18\x01 \x03(\tR\x04idIn\x12%\n" +
	"\fauthor_id_eq\x18\x02 \x01(\tH\x00R\n" +
	"authorIdEq\x88\x01\x01\x12@\n" +
	"\x0ecreated_at_lte\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fcreatedAtLte\x12@\n" +
	"\x0ecreated_at_gte\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fcreatedAtGteB\x0f\n" +
	"\r_author_id_eq\"\x1e\n" +
	"\fOrderByField\x12\x0e\n" +
	"\n" +
	"CREATED_AT\x10\x00\"d\n" +
	"\x14ListProblemsResponse\x12+\n" +
	"\bproblems\x18\x01 \x03(\v2\x0f.tirion.ProblemR\bproblems\x12\x1f\n" +
	"\vtotal_items\x18\x02 \x01(\x04R\n" +
	"totalItems\"\xbb\x01\n" +
	"\x14CreateProblemRequest\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\"\n" +
	"\rtime_limit_ms\x18\x04 \x01(\x03R\vtimeLimitMs\x12&\n" +
	"\x0fmemory_limit_kb\x18\x05 \x01(\x03R\rmemoryLimitKb\"\xf1\x02\n" +
	"\x10ListTestsRequest\x127\n" +
	"\x06filter\x18\x01 \x01(\v2\x1f.tirion.ListTestsRequest.FilterR\x06filter\x12@\n" +
	"\border_by\x18\x02 \x01(\x0e2%.tirion.ListTestsRequest.OrderByFieldR\aorderBy\x12?\n" +
	"\x0forder_direction\x18\x03 \x01(\x0e2\x16.tirion.OrderDirectionR\x0eorderDirection\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.tirion.PaginationR\n" +
	"pagination\x1aM\n" +
	"\x06Filter\x12\"\n" +
	"\rproblem_id_eq\x18\x01 \x01(\tR\vproblemIdEq\x12\x1f\n" +
	"\vwith_hidden\x18\x02 \x01(\bR\n" +
	"withHidden\"\x1e\n" +
	"\fOrderByField\x12\x0e\n" +
	"\n" +
	"CREATED_AT\x10\x00\"X\n" +
	"\x11ListTestsResponse\x12\"\n" +
	"\x05tests\x18\x01 \x03(\v2\f.tirion.TestR\x05tests\x12\x1f\n" +
	"\vtotal_items\x18\x02 \x01(\x04R\n" +
	"totalItems*#\n" +
	"\x0eOrderDirection\x12\a\n" +
	"\x03ASC\x10\x00\x12\b\n" +
	"\x04DESC\x10\x012\x9a\x02\n" +
	"\x06Tirion\x12C\n" +
	"\n" +
	"GetProblem\x12\x19.tirion.GetProblemRequest\x1a\x1a.tirion.GetProblemResponse\x12I\n" +
	"\fListProblems\x12\x1b.tirion.ListProblemsRequest\x1a\x1c.tirion.ListProblemsResponse\x12>\n" +
	"\rCreateProblem\x12\x1c.tirion.CreateProblemRequest\x1a\x0f.tirion.Problem\x12@\n" +
	"\tListTests\x12\x18.tirion.ListTestsRequest\x1a\x19.tirion.ListTestsResponseB3Z1github.com/CodefriendOrg/tirion/pkg/tirion;tirionb\x06proto3"

var (
	file_api_tirion_proto_rawDescOnce sync.Once
	file_api_tirion_proto_rawDescData []byte
)

func file_api_tirion_proto_rawDescGZIP() []byte {
	file_api_tirion_proto_rawDescOnce.Do(func() {
		file_api_tirion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tirion_proto_rawDesc), len(file_api_tirion_proto_rawDesc)))
	})
	return file_api_tirion_proto_rawDescData
}

var file_api_tirion_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_tirion_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_tirion_proto_goTypes = []any{
	(OrderDirection)(0),                   // 0: tirion.OrderDirection
	(ListProblemsRequest_OrderByField)(0), // 1: tirion.ListProblemsRequest.OrderByField
	(ListTestsRequest_OrderByField)(0),    // 2: tirion.ListTestsRequest.OrderByField
	(*Problem)(nil),                       // 3: tirion.Problem
	(*Test)(nil),                          // 4: tirion.Test
	(*Pagination)(nil),                    // 5: tirion.Pagination
	(*GetProblemRequest)(nil),             // 6: tirion.GetProblemRequest
	(*GetProblemResponse)(nil),            // 7: tirion.GetProblemResponse
	(*ListProblemsRequest)(nil),           // 8: tirion.ListProblemsRequest
	(*ListProblemsResponse)(nil),          // 9: tirion.ListProblemsResponse
	(*CreateProblemRequest)(nil),          // 10: tirion.CreateProblemRequest
	(*ListTestsRequest)(nil),              // 11: tirion.ListTestsRequest
	(*ListTestsResponse)(nil),             // 12: tirion.ListTestsResponse
	(*ListProblemsRequest_Filter)(nil),    // 13: tirion.ListProblemsRequest.Filter
	(*ListTestsRequest_Filter)(nil),       // 14: tirion.ListTestsRequest.Filter
	(*timestamppb.Timestamp)(nil),         // 15: google.protobuf.Timestamp
}
var file_api_tirion_proto_depIdxs = []int32{
	15, // 0: tirion.Problem.updated_at:type_name -> google.protobuf.Timestamp
	15, // 1: tirion.Problem.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: tirion.Test.updated_at:type_name -> google.protobuf.Timestamp
	15, // 3: tirion.Test.created_at:type_name -> google.protobuf.Timestamp
	3,  // 4: tirion.GetProblemResponse.problem:type_name -> tirion.Problem
	4,  // 5: tirion.GetProblemResponse.tests:type_name -> tirion.Test
	13, // 6: tirion.ListProblemsRequest.filter:type_name -> tirion.ListProblemsRequest.Filter
	1,  // 7: tirion.ListProblemsRequest.order_by:type_name -> tirion.ListProblemsRequest.OrderByField
	0,  // 8: tirion.ListProblemsRequest.order_direction:type_name -> tirion.OrderDirection
	5,  // 9: tirion.ListProblemsRequest.pagination:type_name -> tirion.Pagination
	3,  // 10: tirion.ListProblemsResponse.problems:type_name -> tirion.Problem
	14, // 11: tirion.ListTestsRequest.filter:type_name -> tirion.ListTestsRequest.Filter
	2,  // 12: tirion.ListTestsRequest.order_by:type_name -> tirion.ListTestsRequest.OrderByField
	0,  // 13: tirion.ListTestsRequest.order_direction:type_name -> tirion.OrderDirection
	5,  // 14: tirion.ListTestsRequest.pagination:type_name -> tirion.Pagination
	4,  // 15: tirion.ListTestsResponse.tests:type_name -> tirion.Test
	15, // 16: tirion.ListProblemsRequest.Filter.created_at_lte:type_name -> google.protobuf.Timestamp
	15, // 17: tirion.ListProblemsRequest.Filter.created_at_gte:type_name -> google.protobuf.Timestamp
	6,  // 18: tirion.Tirion.GetProblem:input_type -> tirion.GetProblemRequest
	8,  // 19: tirion.Tirion.ListProblems:input_type -> tirion.ListProblemsRequest
	10, // 20: tirion.Tirion.CreateProblem:input_type -> tirion.CreateProblemRequest
	11, // 21: tirion.Tirion.ListTests:input_type -> tirion.ListTestsRequest
	7,  // 22: tirion.Tirion.GetProblem:output_type -> tirion.GetProblemResponse
	9,  // 23: tirion.Tirion.ListProblems:output_type -> tirion.ListProblemsResponse
	3,  // 24: tirion.Tirion.CreateProblem:output_type -> tirion.Problem
	12, // 25: tirion.Tirion.ListTests:output_type -> tirion.ListTestsResponse
	22, // [22:26] is the sub-list for method output_type
	18, // [18:22] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_tirion_proto_init() }
func file_api_tirion_proto_init() {
	if File_api_tirion_proto != nil {
		return
	}
	file_api_tirion_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tirion_proto_rawDesc), len(file_api_tirion_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tirion_proto_goTypes,
		DependencyIndexes: file_api_tirion_proto_depIdxs,
		EnumInfos:         file_api_tirion_proto_enumTypes,
		MessageInfos:      file_api_tirion_proto_msgTypes,
	}.Build()
	File_api_tirion_proto = out.File
	file_api_tirion_proto_goTypes = nil
	file_api_tirion_proto_depIdxs = nil
}
