// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/tirion.proto

package tirion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tirion_GetProblem_FullMethodName    = "/tirion.Tirion/GetProblem"
	Tirion_ListProblems_FullMethodName  = "/tirion.Tirion/ListProblems"
	Tirion_CreateProblem_FullMethodName = "/tirion.Tirion/CreateProblem"
	Tirion_ListTests_FullMethodName     = "/tirion.Tirion/ListTests"
)

// TirionClient is the client API for Tirion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TirionClient interface {
	GetProblem(ctx context.Context, in *GetProblemRequest, opts ...grpc.CallOption) (*GetProblemResponse, error)
	ListProblems(ctx context.Context, in *ListProblemsRequest, opts ...grpc.CallOption) (*ListProblemsResponse, error)
	CreateProblem(ctx context.Context, in *CreateProblemRequest, opts ...grpc.CallOption) (*Problem, error)
	ListTests(ctx context.Context, in *ListTestsRequest, opts ...grpc.CallOption) (*ListTestsResponse, error)
}

type tirionClient struct {
	cc grpc.ClientConnInterface
}

func NewTirionClient(cc grpc.ClientConnInterface) TirionClient {
	return &tirionClient{cc}
}

func (c *tirionClient) GetProblem(ctx context.Context, in *GetProblemRequest, opts ...grpc.CallOption) (*GetProblemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProblemResponse)
	err := c.cc.Invoke(ctx, Tirion_GetProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tirionClient) ListProblems(ctx context.Context, in *ListProblemsRequest, opts ...grpc.CallOption) (*ListProblemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProblemsResponse)
	err := c.cc.Invoke(ctx, Tirion_ListProblems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tirionClient) CreateProblem(ctx context.Context, in *CreateProblemRequest, opts ...grpc.CallOption) (*Problem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Problem)
	err := c.cc.Invoke(ctx, Tirion_CreateProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tirionClient) ListTests(ctx context.Context, in *ListTestsRequest, opts ...grpc.CallOption) (*ListTestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTestsResponse)
	err := c.cc.Invoke(ctx, Tirion_ListTests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TirionServer is the server API for Tirion service.
// All implementations must embed UnimplementedTirionServer
// for forward compatibility.
type TirionServer interface {
	GetProblem(context.Context, *GetProblemRequest) (*GetProblemResponse, error)
	ListProblems(context.Context, *ListProblemsRequest) (*ListProblemsResponse, error)
	CreateProblem(context.Context, *CreateProblemRequest) (*Problem, error)
	ListTests(context.Context, *ListTestsRequest) (*ListTestsResponse, error)
	mustEmbedUnimplementedTirionServer()
}

// UnimplementedTirionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTirionServer struct{}

func (UnimplementedTirionServer) GetProblem(context.Context, *GetProblemRequest) (*GetProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProblem not implemented")
}
func (UnimplementedTirionServer) ListProblems(context.Context, *ListProblemsRequest) (*ListProblemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProblems not implemented")
}
func (UnimplementedTirionServer) CreateProblem(context.Context, *CreateProblemRequest) (*Problem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProblem not implemented")
}
func (UnimplementedTirionServer) ListTests(context.Context, *ListTestsRequest) (*ListTestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTests not implemented")
}
func (UnimplementedTirionServer) mustEmbedUnimplementedTirionServer() {}
func (UnimplementedTirionServer) testEmbeddedByValue()                {}

// UnsafeTirionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TirionServer will
// result in compilation errors.
type UnsafeTirionServer interface {
	mustEmbedUnimplementedTirionServer()
}

func RegisterTirionServer(s grpc.ServiceRegistrar, srv TirionServer) {
	// If the following call pancis, it indicates UnimplementedTirionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tirion_ServiceDesc, srv)
}

func _Tirion_GetProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TirionServer).GetProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tirion_GetProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TirionServer).GetProblem(ctx, req.(*GetProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tirion_ListProblems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProblemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TirionServer).ListProblems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tirion_ListProblems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TirionServer).ListProblems(ctx, req.(*ListProblemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tirion_CreateProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TirionServer).CreateProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tirion_CreateProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TirionServer).CreateProblem(ctx, req.(*CreateProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tirion_ListTests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TirionServer).ListTests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tirion_ListTests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TirionServer).ListTests(ctx, req.(*ListTestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tirion_ServiceDesc is the grpc.ServiceDesc for Tirion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tirion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tirion.Tirion",
	HandlerType: (*TirionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProblem",
			Handler:    _Tirion_GetProblem_Handler,
		},
		{
			MethodName: "ListProblems",
			Handler:    _Tirion_ListProblems_Handler,
		},
		{
			MethodName: "CreateProblem",
			Handler:    _Tirion_CreateProblem_Handler,
		},
		{
			MethodName: "ListTests",
			Handler:    _Tirion_ListTests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/tirion.proto",
}
