// Code generated by MockGen. DO NOT EDIT.
// Source: internal\pb\github.com\CodefriendOrg\kingsguard\pkg\kingsguard\kingsguard_grpc.pb.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	kingsguard "github.com/CodefriendOrg/tirion/internal/pb/github.com/CodefriendOrg/kingsguard/pkg/kingsguard"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockKingsguardClient is a mock of KingsguardClient interface.
type MockKingsguardClient struct {
	ctrl     *gomock.Controller
	recorder *MockKingsguardClientMockRecorder
}

// MockKingsguardClientMockRecorder is the mock recorder for MockKingsguardClient.
type MockKingsguardClientMockRecorder struct {
	mock *MockKingsguardClient
}

// NewMockKingsguardClient creates a new mock instance.
func NewMockKingsguardClient(ctrl *gomock.Controller) *MockKingsguardClient {
	mock := &MockKingsguardClient{ctrl: ctrl}
	mock.recorder = &MockKingsguardClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKingsguardClient) EXPECT() *MockKingsguardClientMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockKingsguardClient) GetUser(ctx context.Context, in *kingsguard.GetUserRequest, opts ...grpc.CallOption) (*kingsguard.GetUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUser", varargs...)
	ret0, _ := ret[0].(*kingsguard.GetUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockKingsguardClientMockRecorder) GetUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockKingsguardClient)(nil).GetUser), varargs...)
}

// Login mocks base method.
func (m *MockKingsguardClient) Login(ctx context.Context, in *kingsguard.LoginRequest, opts ...grpc.CallOption) (*kingsguard.LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Login", varargs...)
	ret0, _ := ret[0].(*kingsguard.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockKingsguardClientMockRecorder) Login(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockKingsguardClient)(nil).Login), varargs...)
}

// Register mocks base method.
func (m *MockKingsguardClient) Register(ctx context.Context, in *kingsguard.RegisterRequest, opts ...grpc.CallOption) (*kingsguard.RegisterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Register", varargs...)
	ret0, _ := ret[0].(*kingsguard.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockKingsguardClientMockRecorder) Register(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockKingsguardClient)(nil).Register), varargs...)
}

// ValidateToken mocks base method.
func (m *MockKingsguardClient) ValidateToken(ctx context.Context, in *kingsguard.ValidateTokenRequest, opts ...grpc.CallOption) (*kingsguard.ValidateTokenResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ValidateToken", varargs...)
	ret0, _ := ret[0].(*kingsguard.ValidateTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockKingsguardClientMockRecorder) ValidateToken(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockKingsguardClient)(nil).ValidateToken), varargs...)
}

// MockKingsguardServer is a mock of KingsguardServer interface.
type MockKingsguardServer struct {
	ctrl     *gomock.Controller
	recorder *MockKingsguardServerMockRecorder
}

// MockKingsguardServerMockRecorder is the mock recorder for MockKingsguardServer.
type MockKingsguardServerMockRecorder struct {
	mock *MockKingsguardServer
}

// NewMockKingsguardServer creates a new mock instance.
func NewMockKingsguardServer(ctrl *gomock.Controller) *MockKingsguardServer {
	mock := &MockKingsguardServer{ctrl: ctrl}
	mock.recorder = &MockKingsguardServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKingsguardServer) EXPECT() *MockKingsguardServerMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockKingsguardServer) GetUser(arg0 context.Context, arg1 *kingsguard.GetUserRequest) (*kingsguard.GetUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(*kingsguard.GetUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockKingsguardServerMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockKingsguardServer)(nil).GetUser), arg0, arg1)
}

// Login mocks base method.
func (m *MockKingsguardServer) Login(arg0 context.Context, arg1 *kingsguard.LoginRequest) (*kingsguard.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1)
	ret0, _ := ret[0].(*kingsguard.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockKingsguardServerMockRecorder) Login(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockKingsguardServer)(nil).Login), arg0, arg1)
}

// Register mocks base method.
func (m *MockKingsguardServer) Register(arg0 context.Context, arg1 *kingsguard.RegisterRequest) (*kingsguard.RegisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1)
	ret0, _ := ret[0].(*kingsguard.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockKingsguardServerMockRecorder) Register(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockKingsguardServer)(nil).Register), arg0, arg1)
}

// ValidateToken mocks base method.
func (m *MockKingsguardServer) ValidateToken(arg0 context.Context, arg1 *kingsguard.ValidateTokenRequest) (*kingsguard.ValidateTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", arg0, arg1)
	ret0, _ := ret[0].(*kingsguard.ValidateTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockKingsguardServerMockRecorder) ValidateToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockKingsguardServer)(nil).ValidateToken), arg0, arg1)
}

// mustEmbedUnimplementedKingsguardServer mocks base method.
func (m *MockKingsguardServer) mustEmbedUnimplementedKingsguardServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedKingsguardServer")
}

// mustEmbedUnimplementedKingsguardServer indicates an expected call of mustEmbedUnimplementedKingsguardServer.
func (mr *MockKingsguardServerMockRecorder) mustEmbedUnimplementedKingsguardServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedKingsguardServer", reflect.TypeOf((*MockKingsguardServer)(nil).mustEmbedUnimplementedKingsguardServer))
}

// MockUnsafeKingsguardServer is a mock of UnsafeKingsguardServer interface.
type MockUnsafeKingsguardServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeKingsguardServerMockRecorder
}

// MockUnsafeKingsguardServerMockRecorder is the mock recorder for MockUnsafeKingsguardServer.
type MockUnsafeKingsguardServerMockRecorder struct {
	mock *MockUnsafeKingsguardServer
}

// NewMockUnsafeKingsguardServer creates a new mock instance.
func NewMockUnsafeKingsguardServer(ctrl *gomock.Controller) *MockUnsafeKingsguardServer {
	mock := &MockUnsafeKingsguardServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeKingsguardServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeKingsguardServer) EXPECT() *MockUnsafeKingsguardServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedKingsguardServer mocks base method.
func (m *MockUnsafeKingsguardServer) mustEmbedUnimplementedKingsguardServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedKingsguardServer")
}

// mustEmbedUnimplementedKingsguardServer indicates an expected call of mustEmbedUnimplementedKingsguardServer.
func (mr *MockUnsafeKingsguardServerMockRecorder) mustEmbedUnimplementedKingsguardServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedKingsguardServer", reflect.TypeOf((*MockUnsafeKingsguardServer)(nil).mustEmbedUnimplementedKingsguardServer))
}
