// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/CodefriendOrg/arya/internal/pb/github.com/CodefriendOrg/daenerys/pkg/daenerys"
	"github.com/CodefriendOrg/arya/internal/pb/github.com/CodefriendOrg/tirion/pkg/tirion"
	"github.com/google/uuid"
)

type ListProblemsFilter struct {
	Ids []uuid.UUID `json:"ids,omitempty"`
}

type ListProblemsPagination struct {
	Items    []*tirion.Problem `json:"items,omitempty"`
	PageInfo *PaginationInfo   `json:"pageInfo"`
}

type ListSubmissionPagination struct {
	Items    []*daenerys.Submission `json:"items,omitempty"`
	PageInfo *PaginationInfo        `json:"pageInfo"`
}

type Mutation struct {
}

type Pagination struct {
	Page    int64 `json:"page"`
	PerPage int64 `json:"perPage"`
}

type PaginationInfo struct {
	TotalPages      int64 `json:"totalPages"`
	TotalItems      int64 `json:"totalItems"`
	Page            int64 `json:"page"`
	PerPage         int64 `json:"perPage"`
	HasNextPage     bool  `json:"hasNextPage"`
	HasPreviousPage bool  `json:"hasPreviousPage"`
}

type Query struct {
}

type SendSubmissionInput struct {
	ProblemID           uuid.UUID           `json:"problemId"`
	Code                string              `json:"code"`
	ProgrammingLanguage ProgrammingLanguage `json:"programmingLanguage"`
}

type ProgrammingLanguage string

const (
	ProgrammingLanguageUnknown    ProgrammingLanguage = "UNKNOWN"
	ProgrammingLanguagePython3_12 ProgrammingLanguage = "PYTHON_3_12"
)

var AllProgrammingLanguage = []ProgrammingLanguage{
	ProgrammingLanguageUnknown,
	ProgrammingLanguagePython3_12,
}

func (e ProgrammingLanguage) IsValid() bool {
	switch e {
	case ProgrammingLanguageUnknown, ProgrammingLanguagePython3_12:
		return true
	}
	return false
}

func (e ProgrammingLanguage) String() string {
	return string(e)
}

func (e *ProgrammingLanguage) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProgrammingLanguage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProgrammingLanguage", str)
	}
	return nil
}

func (e ProgrammingLanguage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProgrammingLanguage) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProgrammingLanguage) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SubmissionStatus string

const (
	SubmissionStatusUnknown             SubmissionStatus = "UNKNOWN"
	SubmissionStatusNew                 SubmissionStatus = "NEW"
	SubmissionStatusJudging             SubmissionStatus = "JUDGING"
	SubmissionStatusOk                  SubmissionStatus = "OK"
	SubmissionStatusWrongAnswer         SubmissionStatus = "WRONG_ANSWER"
	SubmissionStatusRuntimeError        SubmissionStatus = "RUNTIME_ERROR"
	SubmissionStatusTimeLimitExceeded   SubmissionStatus = "TIME_LIMIT_EXCEEDED"
	SubmissionStatusMemoryLimitExceeded SubmissionStatus = "MEMORY_LIMIT_EXCEEDED"
	SubmissionStatusCompilationError    SubmissionStatus = "COMPILATION_ERROR"
)

var AllSubmissionStatus = []SubmissionStatus{
	SubmissionStatusUnknown,
	SubmissionStatusNew,
	SubmissionStatusJudging,
	SubmissionStatusOk,
	SubmissionStatusWrongAnswer,
	SubmissionStatusRuntimeError,
	SubmissionStatusTimeLimitExceeded,
	SubmissionStatusMemoryLimitExceeded,
	SubmissionStatusCompilationError,
}

func (e SubmissionStatus) IsValid() bool {
	switch e {
	case SubmissionStatusUnknown, SubmissionStatusNew, SubmissionStatusJudging, SubmissionStatusOk, SubmissionStatusWrongAnswer, SubmissionStatusRuntimeError, SubmissionStatusTimeLimitExceeded, SubmissionStatusMemoryLimitExceeded, SubmissionStatusCompilationError:
		return true
	}
	return false
}

func (e SubmissionStatus) String() string {
	return string(e)
}

func (e *SubmissionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SubmissionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SubmissionStatus", str)
	}
	return nil
}

func (e SubmissionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SubmissionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SubmissionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
