// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: vendor.protogen/github.com/CodefriendOrg/daenerys/api/daenerys.proto

package daenerys

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Daenerys_SendSubmission_FullMethodName         = "/daenerys.Daenerys/SendSubmission"
	Daenerys_UpdateSubmissionStatus_FullMethodName = "/daenerys.Daenerys/UpdateSubmissionStatus"
	Daenerys_GetSubmission_FullMethodName          = "/daenerys.Daenerys/GetSubmission"
	Daenerys_ListSubmissions_FullMethodName        = "/daenerys.Daenerys/ListSubmissions"
)

// DaenerysClient is the client API for Daenerys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaenerysClient interface {
	SendSubmission(ctx context.Context, in *SendSubmissionRequest, opts ...grpc.CallOption) (*Submission, error)
	UpdateSubmissionStatus(ctx context.Context, in *UpdateSubmissionStatusRequest, opts ...grpc.CallOption) (*Submission, error)
	GetSubmission(ctx context.Context, in *GetSubmissionRequest, opts ...grpc.CallOption) (*Submission, error)
	ListSubmissions(ctx context.Context, in *ListSubmissionsRequest, opts ...grpc.CallOption) (*ListSubmissionsResponse, error)
}

type daenerysClient struct {
	cc grpc.ClientConnInterface
}

func NewDaenerysClient(cc grpc.ClientConnInterface) DaenerysClient {
	return &daenerysClient{cc}
}

func (c *daenerysClient) SendSubmission(ctx context.Context, in *SendSubmissionRequest, opts ...grpc.CallOption) (*Submission, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Submission)
	err := c.cc.Invoke(ctx, Daenerys_SendSubmission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daenerysClient) UpdateSubmissionStatus(ctx context.Context, in *UpdateSubmissionStatusRequest, opts ...grpc.CallOption) (*Submission, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Submission)
	err := c.cc.Invoke(ctx, Daenerys_UpdateSubmissionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daenerysClient) GetSubmission(ctx context.Context, in *GetSubmissionRequest, opts ...grpc.CallOption) (*Submission, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Submission)
	err := c.cc.Invoke(ctx, Daenerys_GetSubmission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daenerysClient) ListSubmissions(ctx context.Context, in *ListSubmissionsRequest, opts ...grpc.CallOption) (*ListSubmissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubmissionsResponse)
	err := c.cc.Invoke(ctx, Daenerys_ListSubmissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaenerysServer is the server API for Daenerys service.
// All implementations must embed UnimplementedDaenerysServer
// for forward compatibility.
type DaenerysServer interface {
	SendSubmission(context.Context, *SendSubmissionRequest) (*Submission, error)
	UpdateSubmissionStatus(context.Context, *UpdateSubmissionStatusRequest) (*Submission, error)
	GetSubmission(context.Context, *GetSubmissionRequest) (*Submission, error)
	ListSubmissions(context.Context, *ListSubmissionsRequest) (*ListSubmissionsResponse, error)
	mustEmbedUnimplementedDaenerysServer()
}

// UnimplementedDaenerysServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaenerysServer struct{}

func (UnimplementedDaenerysServer) SendSubmission(context.Context, *SendSubmissionRequest) (*Submission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSubmission not implemented")
}
func (UnimplementedDaenerysServer) UpdateSubmissionStatus(context.Context, *UpdateSubmissionStatusRequest) (*Submission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubmissionStatus not implemented")
}
func (UnimplementedDaenerysServer) GetSubmission(context.Context, *GetSubmissionRequest) (*Submission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubmission not implemented")
}
func (UnimplementedDaenerysServer) ListSubmissions(context.Context, *ListSubmissionsRequest) (*ListSubmissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSubmissions not implemented")
}
func (UnimplementedDaenerysServer) mustEmbedUnimplementedDaenerysServer() {}
func (UnimplementedDaenerysServer) testEmbeddedByValue()                  {}

// UnsafeDaenerysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaenerysServer will
// result in compilation errors.
type UnsafeDaenerysServer interface {
	mustEmbedUnimplementedDaenerysServer()
}

func RegisterDaenerysServer(s grpc.ServiceRegistrar, srv DaenerysServer) {
	// If the following call pancis, it indicates UnimplementedDaenerysServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Daenerys_ServiceDesc, srv)
}

func _Daenerys_SendSubmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaenerysServer).SendSubmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daenerys_SendSubmission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaenerysServer).SendSubmission(ctx, req.(*SendSubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daenerys_UpdateSubmissionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubmissionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaenerysServer).UpdateSubmissionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daenerys_UpdateSubmissionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaenerysServer).UpdateSubmissionStatus(ctx, req.(*UpdateSubmissionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daenerys_GetSubmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaenerysServer).GetSubmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daenerys_GetSubmission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaenerysServer).GetSubmission(ctx, req.(*GetSubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daenerys_ListSubmissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubmissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaenerysServer).ListSubmissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daenerys_ListSubmissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaenerysServer).ListSubmissions(ctx, req.(*ListSubmissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Daenerys_ServiceDesc is the grpc.ServiceDesc for Daenerys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Daenerys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "daenerys.Daenerys",
	HandlerType: (*DaenerysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSubmission",
			Handler:    _Daenerys_SendSubmission_Handler,
		},
		{
			MethodName: "UpdateSubmissionStatus",
			Handler:    _Daenerys_UpdateSubmissionStatus_Handler,
		},
		{
			MethodName: "GetSubmission",
			Handler:    _Daenerys_GetSubmission_Handler,
		},
		{
			MethodName: "ListSubmissions",
			Handler:    _Daenerys_ListSubmissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vendor.protogen/github.com/CodefriendOrg/daenerys/api/daenerys.proto",
}
