// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/daenerys.proto

package daenerys

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderDirection int32

const (
	OrderDirection_ASC  OrderDirection = 0
	OrderDirection_DESC OrderDirection = 1
)

// Enum value maps for OrderDirection.
var (
	OrderDirection_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	OrderDirection_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x OrderDirection) Enum() *OrderDirection {
	p := new(OrderDirection)
	*p = x
	return p
}

func (x OrderDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_api_daenerys_proto_enumTypes[0].Descriptor()
}

func (OrderDirection) Type() protoreflect.EnumType {
	return &file_api_daenerys_proto_enumTypes[0]
}

func (x OrderDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderDirection.Descriptor instead.
func (OrderDirection) EnumDescriptor() ([]byte, []int) {
	return file_api_daenerys_proto_rawDescGZIP(), []int{0}
}

type ProgrammingLanguage int32

const (
	ProgrammingLanguage_LANGUAGE_UNKNOWN     ProgrammingLanguage = 0
	ProgrammingLanguage_LANGUAGE_PYTHON_3_12 ProgrammingLanguage = 1
)

// Enum value maps for ProgrammingLanguage.
var (
	ProgrammingLanguage_name = map[int32]string{
		0: "LANGUAGE_UNKNOWN",
		1: "LANGUAGE_PYTHON_3_12",
	}
	ProgrammingLanguage_value = map[string]int32{
		"LANGUAGE_UNKNOWN":     0,
		"LANGUAGE_PYTHON_3_12": 1,
	}
)

func (x ProgrammingLanguage) Enum() *ProgrammingLanguage {
	p := new(ProgrammingLanguage)
	*p = x
	return p
}

func (x ProgrammingLanguage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProgrammingLanguage) Descriptor() protoreflect.EnumDescriptor {
	return file_api_daenerys_proto_enumTypes[1].Descriptor()
}

func (ProgrammingLanguage) Type() protoreflect.EnumType {
	return &file_api_daenerys_proto_enumTypes[1]
}

func (x ProgrammingLanguage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProgrammingLanguage.Descriptor instead.
func (ProgrammingLanguage) EnumDescriptor() ([]byte, []int) {
	return file_api_daenerys_proto_rawDescGZIP(), []int{1}
}

type SubmissionStatus int32

const (
	SubmissionStatus_STATUS_UNKNOWN               SubmissionStatus = 0
	SubmissionStatus_STATUS_NEW                   SubmissionStatus = 1
	SubmissionStatus_STATUS_JUDGING               SubmissionStatus = 2
	SubmissionStatus_STATUS_OK                    SubmissionStatus = 3
	SubmissionStatus_STATUS_WRONG_ANSWER          SubmissionStatus = 4
	SubmissionStatus_STATUS_RUNTIME_ERROR         SubmissionStatus = 5
	SubmissionStatus_STATUS_TIME_LIMIT_EXCEEDED   SubmissionStatus = 6
	SubmissionStatus_STATUS_MEMORY_LIMIT_EXCEEDED SubmissionStatus = 7
	SubmissionStatus_STATUS_COMPILATION_ERROR     SubmissionStatus = 8
	SubmissionStatus_STATUS_INTERNAL_ERROR        SubmissionStatus = 9
)

// Enum value maps for SubmissionStatus.
var (
	SubmissionStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_NEW",
		2: "STATUS_JUDGING",
		3: "STATUS_OK",
		4: "STATUS_WRONG_ANSWER",
		5: "STATUS_RUNTIME_ERROR",
		6: "STATUS_TIME_LIMIT_EXCEEDED",
		7: "STATUS_MEMORY_LIMIT_EXCEEDED",
		8: "STATUS_COMPILATION_ERROR",
		9: "STATUS_INTERNAL_ERROR",
	}
	SubmissionStatus_value = map[string]int32{
		"STATUS_UNKNOWN":               0,
		"STATUS_NEW":                   1,
		"STATUS_JUDGING":               2,
		"STATUS_OK":                    3,
		"STATUS_WRONG_ANSWER":          4,
		"STATUS_RUNTIME_ERROR":         5,
		"STATUS_TIME_LIMIT_EXCEEDED":   6,
		"STATUS_MEMORY_LIMIT_EXCEEDED": 7,
		"STATUS_COMPILATION_ERROR":     8,
		"STATUS_INTERNAL_ERROR":        9,
	}
)

func (x SubmissionStatus) Enum() *SubmissionStatus {
	p := new(SubmissionStatus)
	*p = x
	return p
}

func (x SubmissionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubmissionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_daenerys_proto_enumTypes[2].Descriptor()
}

func (SubmissionStatus) Type() protoreflect.EnumType {
	return &file_api_daenerys_proto_enumTypes[2]
}

func (x SubmissionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubmissionStatus.Descriptor instead.
func (SubmissionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_daenerys_proto_rawDescGZIP(), []int{2}
}

type ListSubmissionsRequest_OrderByField int32

const (
	ListSubmissionsRequest_CREATED_AT ListSubmissionsRequest_OrderByField = 0
)

// Enum value maps for ListSubmissionsRequest_OrderByField.
var (
	ListSubmissionsRequest_OrderByField_name = map[int32]string{
		0: "CREATED_AT",
	}
	ListSubmissionsRequest_OrderByField_value = map[string]int32{
		"CREATED_AT": 0,
	}
)

func (x ListSubmissionsRequest_OrderByField) Enum() *ListSubmissionsRequest_OrderByField {
	p := new(ListSubmissionsRequest_OrderByField)
	*p = x
	return p
}

func (x ListSubmissionsRequest_OrderByField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListSubmissionsRequest_OrderByField) Descriptor() protoreflect.EnumDescriptor {
	return file_api_daenerys_proto_enumTypes[3].Descriptor()
}

func (ListSubmissionsRequest_OrderByField) Type() protoreflect.EnumType {
	return &file_api_daenerys_proto_enumTypes[3]
}

func (x ListSubmissionsRequest_OrderByField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListSubmissionsRequest_OrderByField.Descriptor instead.
func (ListSubmissionsRequest_OrderByField) EnumDescriptor() ([]byte, []int) {
	return file_api_daenerys_proto_rawDescGZIP(), []int{5, 0}
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       uint64                 `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_api_daenerys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_api_daenerys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_api_daenerys_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPerPage() uint64 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type Submission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID задачи (UUID)
	ProblemId string `protobuf:"bytes,2,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	// ID пользователя (UUID)
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Статус проверки решения
	Status SubmissionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=daenerys.SubmissionStatus" json:"status,omitempty"`
	// Код решения пользователя
	Code string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	// Язык программирования решения
	Language ProgrammingLanguage `protobuf:"varint,6,opt,name=language,proto3,enum=daenerys.ProgrammingLanguage" json:"language,omitempty"`
	// Время последнего обновление
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Время создания
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Submission) Reset() {
	*x = Submission{}
	mi := &file_api_daenerys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Submission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submission) ProtoMessage() {}

func (x *Submission) ProtoReflect() protoreflect.Message {
	mi := &file_api_daenerys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Submission.ProtoReflect.Descriptor instead.
func (*Submission) Descriptor() ([]byte, []int) {
	return file_api_daenerys_proto_rawDescGZIP(), []int{1}
}

func (x *Submission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Submission) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *Submission) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Submission) GetStatus() SubmissionStatus {
	if x != nil {
		return x.Status
	}
	return SubmissionStatus_STATUS_UNKNOWN
}

func (x *Submission) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Submission) GetLanguage() ProgrammingLanguage {
	if x != nil {
		return x.Language
	}
	return ProgrammingLanguage_LANGUAGE_UNKNOWN
}

func (x *Submission) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Submission) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SendSubmissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     string                 `protobuf:"bytes,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Language      ProgrammingLanguage    `protobuf:"varint,4,opt,name=language,proto3,enum=daenerys.ProgrammingLanguage" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSubmissionRequest) Reset() {
	*x = SendSubmissionRequest{}
	mi := &file_api_daenerys_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSubmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSubmissionRequest) ProtoMessage() {}

func (x *SendSubmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_daenerys_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSubmissionRequest.ProtoReflect.Descriptor instead.
func (*SendSubmissionRequest) Descriptor() ([]byte, []int) {
	return file_api_daenerys_proto_rawDescGZIP(), []int{2}
}

func (x *SendSubmissionRequest) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *SendSubmissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendSubmissionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SendSubmissionRequest) GetLanguage() ProgrammingLanguage {
	if x != nil {
		return x.Language
	}
	return ProgrammingLanguage_LANGUAGE_UNKNOWN
}

type UpdateSubmissionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        SubmissionStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=daenerys.SubmissionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubmissionStatusRequest) Reset() {
	*x = UpdateSubmissionStatusRequest{}
	mi := &file_api_daenerys_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubmissionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubmissionStatusRequest) ProtoMessage() {}

func (x *UpdateSubmissionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_daenerys_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubmissionStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubmissionStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_daenerys_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSubmissionStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSubmissionStatusRequest) GetStatus() SubmissionStatus {
	if x != nil {
		return x.Status
	}
	return SubmissionStatus_STATUS_UNKNOWN
}

type GetSubmissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubmissionRequest) Reset() {
	*x = GetSubmissionRequest{}
	mi := &file_api_daenerys_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubmissionRequest) ProtoMessage() {}

func (x *GetSubmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_daenerys_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubmissionRequest.ProtoReflect.Descriptor instead.
func (*GetSubmissionRequest) Descriptor() ([]byte, []int) {
	return file_api_daenerys_proto_rawDescGZIP(), []int{4}
}

func (x *GetSubmissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListSubmissionsRequest struct {
	state          protoimpl.MessageState              `protogen:"open.v1"`
	Filter         *ListSubmissionsRequest_Filter      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy        ListSubmissionsRequest_OrderByField `protobuf:"varint,2,opt,name=order_by,json=orderBy,proto3,enum=daenerys.ListSubmissionsRequest_OrderByField" json:"order_by,omitempty"`
	OrderDirection OrderDirection                      `protobuf:"varint,3,opt,name=order_direction,json=orderDirection,proto3,enum=daenerys.OrderDirection" json:"order_direction,omitempty"`
	Pagination     *Pagination                         `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListSubmissionsRequest) Reset() {
	*x = ListSubmissionsRequest{}
	mi := &file_api_daenerys_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubmissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubmissionsRequest) ProtoMessage() {}

func (x *ListSubmissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_daenerys_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubmissionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubmissionsRequest) Descriptor() ([]byte, []int) {
	return file_api_daenerys_proto_rawDescGZIP(), []int{5}
}

func (x *ListSubmissionsRequest) GetFilter() *ListSubmissionsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListSubmissionsRequest) GetOrderBy() ListSubmissionsRequest_OrderByField {
	if x != nil {
		return x.OrderBy
	}
	return ListSubmissionsRequest_CREATED_AT
}

func (x *ListSubmissionsRequest) GetOrderDirection() OrderDirection {
	if x != nil {
		return x.OrderDirection
	}
	return OrderDirection_ASC
}

func (x *ListSubmissionsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListSubmissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submissions   []*Submission          `protobuf:"bytes,1,rep,name=submissions,proto3" json:"submissions,omitempty"`
	TotalItems    uint64                 `protobuf:"varint,2,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubmissionsResponse) Reset() {
	*x = ListSubmissionsResponse{}
	mi := &file_api_daenerys_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubmissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubmissionsResponse) ProtoMessage() {}

func (x *ListSubmissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_daenerys_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubmissionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubmissionsResponse) Descriptor() ([]byte, []int) {
	return file_api_daenerys_proto_rawDescGZIP(), []int{6}
}

func (x *ListSubmissionsResponse) GetSubmissions() []*Submission {
	if x != nil {
		return x.Submissions
	}
	return nil
}

func (x *ListSubmissionsResponse) GetTotalItems() uint64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

type ListSubmissionsRequest_Filter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubmissionIdIn []string               `protobuf:"bytes,1,rep,name=submission_id_in,json=submissionIdIn,proto3" json:"submission_id_in,omitempty"`
	ProblemIdEq    *string                `protobuf:"bytes,2,opt,name=problem_id_eq,json=problemIdEq,proto3,oneof" json:"problem_id_eq,omitempty"`
	UserIdEq       *string                `protobuf:"bytes,3,opt,name=user_id_eq,json=userIdEq,proto3,oneof" json:"user_id_eq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListSubmissionsRequest_Filter) Reset() {
	*x = ListSubmissionsRequest_Filter{}
	mi := &file_api_daenerys_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubmissionsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubmissionsRequest_Filter) ProtoMessage() {}

func (x *ListSubmissionsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_api_daenerys_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubmissionsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListSubmissionsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_api_daenerys_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListSubmissionsRequest_Filter) GetSubmissionIdIn() []string {
	if x != nil {
		return x.SubmissionIdIn
	}
	return nil
}

func (x *ListSubmissionsRequest_Filter) GetProblemIdEq() string {
	if x != nil && x.ProblemIdEq != nil {
		return *x.ProblemIdEq
	}
	return ""
}

func (x *ListSubmissionsRequest_Filter) GetUserIdEq() string {
	if x != nil && x.UserIdEq != nil {
		return *x.UserIdEq
	}
	return ""
}

var File_api_daenerys_proto protoreflect.FileDescriptor

const file_api_daenerys_proto_rawDesc = "" +
	"\n" +
	"\x12api/daenerys.proto\x12\bdaenerys\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x04R\aperPage\"\xcd\x02\n" +
	"\n" +
	"Submission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x02 \x01(\tR\tproblemId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.daenerys.SubmissionStatusR\x06status\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x129\n" +
	"\blanguage\x18\x06 \x01(\x0e2\x1d.daenerys.ProgrammingLanguageR\blanguage\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9e\x01\n" +
	"\x15SendSubmissionRequest\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\tR\tproblemId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x129\n" +
	"\blanguage\x18\x04 \x01(\x0e2\x1d.daenerys.ProgrammingLanguageR\blanguage\"c\n" +
	"\x1dUpdateSubmissionStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.daenerys.SubmissionStatusR\x06status\"&\n" +
	"\x14GetSubmissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xde\x03\n" +
	"\x16ListSubmissionsRequest\x12?\n" +
	"\x06filter\x18\x01 \x01(\v2'.daenerys.ListSubmissionsRequest.FilterR\x06filter\x12H\n" +
	"\border_by\x18\x02 \x01(\x0e2-.daenerys.ListSubmissionsRequest.OrderByFieldR\aorderBy\x12A\n" +
	"\x0forder_direction\x18\x03 \x01(\x0e2\x18.daenerys.OrderDirectionR\x0eorderDirection\x124\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x14.daenerys.PaginationR\n" +
	"pagination\x1a\x9f\x01\n" +
	"\x06Filter\x12(\n" +
	"\x10submission_id_in\x18\x01 \x03(\tR\x0esubmissionIdIn\x12'\n" +
	"\rproblem_id_eq\x18\x02 \x01(\tH\x00R\vproblemIdEq\x88\x01\x01\x12!\n" +
	"\n" +
	"user_id_eq\x18\x03 \x01(\tH\x01R\buserIdEq\x88\x01\x01B\x10\n" +
	"\x0e_problem_id_eqB\r\n" +
	"\v_user_id_eq\"\x1e\n" +
	"\fOrderByField\x12\x0e\n" +
	"\n" +
	"CREATED_AT\x10\x00\"r\n" +
	"\x17ListSubmissionsResponse\x126\n" +
	"\vsubmissions\x18\x01 \x03(\v2\x14.daenerys.SubmissionR\vsubmissions\x12\x1f\n" +
	"\vtotal_items\x18\x02 \x01(\x04R\n" +
	"totalItems*#\n" +
	"\x0eOrderDirection\x12\a\n" +
	"\x03ASC\x10\x00\x12\b\n" +
	"\x04DESC\x10\x01*E\n" +
	"\x13ProgrammingLanguage\x12\x14\n" +
	"\x10LANGUAGE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14LANGUAGE_PYTHON_3_12\x10\x01*\x87\x02\n" +
	"\x10SubmissionStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"STATUS_NEW\x10\x01\x12\x12\n" +
	"\x0eSTATUS_JUDGING\x10\x02\x12\r\n" +
	"\tSTATUS_OK\x10\x03\x12\x17\n" +
	"\x13STATUS_WRONG_ANSWER\x10\x04\x12\x18\n" +
	"\x14STATUS_RUNTIME_ERROR\x10\x05\x12\x1e\n" +
	"\x1aSTATUS_TIME_LIMIT_EXCEEDED\x10\x06\x12 \n" +
	"\x1cSTATUS_MEMORY_LIMIT_EXCEEDED\x10\a\x12\x1c\n" +
	"\x18STATUS_COMPILATION_ERROR\x10\b\x12\x19\n" +
	"\x15STATUS_INTERNAL_ERROR\x10\t2\xcb\x02\n" +
	"\bDaenerys\x12G\n" +
	"\x0eSendSubmission\x12\x1f.daenerys.SendSubmissionRequest\x1a\x14.daenerys.Submission\x12W\n" +
	"\x16UpdateSubmissionStatus\x12'.daenerys.UpdateSubmissionStatusRequest\x1a\x14.daenerys.Submission\x12E\n" +
	"\rGetSubmission\x12\x1e.daenerys.GetSubmissionRequest\x1a\x14.daenerys.Submission\x12V\n" +
	"\x0fListSubmissions\x12 .daenerys.ListSubmissionsRequest\x1a!.daenerys.ListSubmissionsResponseB9Z7github.com/CodefriendOrg/daenerys/pkg/daenerys;daenerysb\x06proto3"

var (
	file_api_daenerys_proto_rawDescOnce sync.Once
	file_api_daenerys_proto_rawDescData []byte
)

func file_api_daenerys_proto_rawDescGZIP() []byte {
	file_api_daenerys_proto_rawDescOnce.Do(func() {
		file_api_daenerys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_daenerys_proto_rawDesc), len(file_api_daenerys_proto_rawDesc)))
	})
	return file_api_daenerys_proto_rawDescData
}

var file_api_daenerys_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_daenerys_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_daenerys_proto_goTypes = []any{
	(OrderDirection)(0),                      // 0: daenerys.OrderDirection
	(ProgrammingLanguage)(0),                 // 1: daenerys.ProgrammingLanguage
	(SubmissionStatus)(0),                    // 2: daenerys.SubmissionStatus
	(ListSubmissionsRequest_OrderByField)(0), // 3: daenerys.ListSubmissionsRequest.OrderByField
	(*Pagination)(nil),                       // 4: daenerys.Pagination
	(*Submission)(nil),                       // 5: daenerys.Submission
	(*SendSubmissionRequest)(nil),            // 6: daenerys.SendSubmissionRequest
	(*UpdateSubmissionStatusRequest)(nil),    // 7: daenerys.UpdateSubmissionStatusRequest
	(*GetSubmissionRequest)(nil),             // 8: daenerys.GetSubmissionRequest
	(*ListSubmissionsRequest)(nil),           // 9: daenerys.ListSubmissionsRequest
	(*ListSubmissionsResponse)(nil),          // 10: daenerys.ListSubmissionsResponse
	(*ListSubmissionsRequest_Filter)(nil),    // 11: daenerys.ListSubmissionsRequest.Filter
	(*timestamppb.Timestamp)(nil),            // 12: google.protobuf.Timestamp
}
var file_api_daenerys_proto_depIdxs = []int32{
	2,  // 0: daenerys.Submission.status:type_name -> daenerys.SubmissionStatus
	1,  // 1: daenerys.Submission.language:type_name -> daenerys.ProgrammingLanguage
	12, // 2: daenerys.Submission.updated_at:type_name -> google.protobuf.Timestamp
	12, // 3: daenerys.Submission.created_at:type_name -> google.protobuf.Timestamp
	1,  // 4: daenerys.SendSubmissionRequest.language:type_name -> daenerys.ProgrammingLanguage
	2,  // 5: daenerys.UpdateSubmissionStatusRequest.status:type_name -> daenerys.SubmissionStatus
	11, // 6: daenerys.ListSubmissionsRequest.filter:type_name -> daenerys.ListSubmissionsRequest.Filter
	3,  // 7: daenerys.ListSubmissionsRequest.order_by:type_name -> daenerys.ListSubmissionsRequest.OrderByField
	0,  // 8: daenerys.ListSubmissionsRequest.order_direction:type_name -> daenerys.OrderDirection
	4,  // 9: daenerys.ListSubmissionsRequest.pagination:type_name -> daenerys.Pagination
	5,  // 10: daenerys.ListSubmissionsResponse.submissions:type_name -> daenerys.Submission
	6,  // 11: daenerys.Daenerys.SendSubmission:input_type -> daenerys.SendSubmissionRequest
	7,  // 12: daenerys.Daenerys.UpdateSubmissionStatus:input_type -> daenerys.UpdateSubmissionStatusRequest
	8,  // 13: daenerys.Daenerys.GetSubmission:input_type -> daenerys.GetSubmissionRequest
	9,  // 14: daenerys.Daenerys.ListSubmissions:input_type -> daenerys.ListSubmissionsRequest
	5,  // 15: daenerys.Daenerys.SendSubmission:output_type -> daenerys.Submission
	5,  // 16: daenerys.Daenerys.UpdateSubmissionStatus:output_type -> daenerys.Submission
	5,  // 17: daenerys.Daenerys.GetSubmission:output_type -> daenerys.Submission
	10, // 18: daenerys.Daenerys.ListSubmissions:output_type -> daenerys.ListSubmissionsResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_daenerys_proto_init() }
func file_api_daenerys_proto_init() {
	if File_api_daenerys_proto != nil {
		return
	}
	file_api_daenerys_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_daenerys_proto_rawDesc), len(file_api_daenerys_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_daenerys_proto_goTypes,
		DependencyIndexes: file_api_daenerys_proto_depIdxs,
		EnumInfos:         file_api_daenerys_proto_enumTypes,
		MessageInfos:      file_api_daenerys_proto_msgTypes,
	}.Build()
	File_api_daenerys_proto = out.File
	file_api_daenerys_proto_goTypes = nil
	file_api_daenerys_proto_depIdxs = nil
}
