package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"time"

	"github.com/CodefriendOrg/arya/internal/app/graph/generated"
	"github.com/CodefriendOrg/arya/internal/pb/github.com/CodefriendOrg/tirion/pkg/tirion"
	"github.com/google/uuid"
	"github.com/samber/lo"
)

// ID is the resolver for the id field.
func (r *problemResolver) ID(ctx context.Context, obj *tirion.Problem) (uuid.UUID, error) {
	if obj == nil {
		return uuid.Nil, nil
	}

	return uuid.MustParse(obj.Id), nil
}

// CreatedAt is the resolver for the created_at field.
func (r *problemResolver) CreatedAt(ctx context.Context, obj *tirion.Problem) (*time.Time, error) {
	if obj == nil {
		return nil, nil
	}

	return lo.ToPtr(obj.CreatedAt.AsTime()), nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *problemResolver) UpdatedAt(ctx context.Context, obj *tirion.Problem) (*time.Time, error) {
	if obj == nil {
		return nil, nil
	}

	return lo.ToPtr(obj.UpdatedAt.AsTime()), nil
}

// Tests is the resolver for the tests field.
func (r *problemResolver) Tests(ctx context.Context, obj *tirion.Problem) ([]*tirion.Test, error) {
	if obj == nil {
		return nil, nil
	}

	// TODO: Добавить dataloader
	tests, err := r.tirionHelper.GetTestsByProblem(ctx, uuid.MustParse(obj.Id))
	if err != nil {
		return nil, err
	}

	return tests, nil
}

// Problem returns generated.ProblemResolver implementation.
func (r *Resolver) Problem() generated.ProblemResolver { return &problemResolver{r} }

type problemResolver struct{ *Resolver }
