package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/CodefriendOrg/arya/internal/pkg/model"
)

// ListProblems is the resolver for the listProblems field.
func (r *queryResolver) ListProblems(ctx context.Context, filter *model.ListProblemsFilter, pagination model.Pagination) (*model.ListProblemsPagination, error) {
	problems, count, err := r.tirionHelper.ListProblems(ctx, filter, pagination)
	if err != nil {
		return nil, err
	}

	return &model.ListProblemsPagination{
		Items:    problems,
		PageInfo: r.buildPaginationPageInfo(pagination.Page, pagination.PerPage, count),
	}, nil
}
