package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/CodefriendOrg/arya/internal/app/graph/generated"
	"github.com/CodefriendOrg/arya/internal/pb/github.com/CodefriendOrg/daenerys/pkg/daenerys"
	"github.com/CodefriendOrg/arya/internal/pkg/model"
	"github.com/google/uuid"
)

// GetSubmission is the resolver for the getSubmission field.
func (r *queryResolver) GetSubmission(ctx context.Context, id uuid.UUID) (*daenerys.Submission, error) {
	return r.daenerysHelper.GetSubmissionByID(ctx, id)
}

// ListSubmissions is the resolver for the listSubmissions field.
func (r *queryResolver) ListSubmissions(ctx context.Context, problemID uuid.UUID, pagination model.Pagination) (*model.ListSubmissionPagination, error) {
	submissions, totalItems, err := r.daenerysHelper.GetSubmissionsByProblem(ctx, problemID, pagination)
	if err != nil {
		return nil, err
	}

	return &model.ListSubmissionPagination{
		Items:    submissions,
		PageInfo: r.buildPaginationPageInfo(pagination.Page, pagination.PerPage, totalItems),
	}, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
