package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/CodefriendOrg/arya/internal/pb/github.com/CodefriendOrg/daenerys/pkg/daenerys"
	"github.com/CodefriendOrg/arya/internal/pkg/model"
)

// SendSubmission is the resolver for the sendSubmission field.
func (r *mutationResolver) SendSubmission(ctx context.Context, input model.SendSubmissionInput) (*daenerys.Submission, error) {
	submission, err := r.daenerysHelper.SendSubmission(ctx, input.ProblemID, input.Code, input.ProgrammingLanguage)
	if err != nil {
		return nil, err
	}

	return submission, nil
}
