package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"time"

	"github.com/CodefriendOrg/arya/internal/app/graph/generated"
	"github.com/CodefriendOrg/arya/internal/pb/github.com/CodefriendOrg/daenerys/pkg/daenerys"
	"github.com/CodefriendOrg/arya/internal/pkg/model"
	"github.com/google/uuid"
	"github.com/samber/lo"
)

// ID is the resolver for the id field.
func (r *submissionResolver) ID(ctx context.Context, obj *daenerys.Submission) (uuid.UUID, error) {
	if obj == nil {
		return uuid.Nil, nil
	}

	return uuid.MustParse(obj.Id), nil
}

// ProblemID is the resolver for the problemId field.
func (r *submissionResolver) ProblemID(ctx context.Context, obj *daenerys.Submission) (uuid.UUID, error) {
	if obj == nil {
		return uuid.Nil, nil
	}

	return uuid.MustParse(obj.ProblemId), nil
}

// UserID is the resolver for the userId field.
func (r *submissionResolver) UserID(ctx context.Context, obj *daenerys.Submission) (uuid.UUID, error) {
	if obj == nil {
		return uuid.Nil, nil
	}

	return uuid.MustParse(obj.UserId), nil
}

// SubmissionStatus is the resolver for the submissionStatus field.
func (r *submissionResolver) SubmissionStatus(ctx context.Context, obj *daenerys.Submission) (model.SubmissionStatus, error) {
	if obj == nil {
		return model.SubmissionStatusUnknown, nil
	}

	return model.ConvertSubmissionStatus(obj.Status), nil
}

// Language is the resolver for the language field.
func (r *submissionResolver) Language(ctx context.Context, obj *daenerys.Submission) (model.ProgrammingLanguage, error) {
	if obj == nil {
		return model.ProgrammingLanguageUnknown, nil
	}

	return model.ConvertProgrammingLanguage(obj.Language), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *submissionResolver) CreatedAt(ctx context.Context, obj *daenerys.Submission) (*time.Time, error) {
	if obj == nil {
		return nil, nil
	}

	return lo.ToPtr(obj.CreatedAt.AsTime()), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *submissionResolver) UpdatedAt(ctx context.Context, obj *daenerys.Submission) (*time.Time, error) {
	if obj == nil {
		return nil, nil
	}

	return lo.ToPtr(obj.UpdatedAt.AsTime()), nil
}

// Submission returns generated.SubmissionResolver implementation.
func (r *Resolver) Submission() generated.SubmissionResolver { return &submissionResolver{r} }

type submissionResolver struct{ *Resolver }
