package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/CodefriendOrg/arya/internal/app/graph/generated"
	"github.com/CodefriendOrg/arya/internal/pb/github.com/CodefriendOrg/tirion/pkg/tirion"
	"github.com/google/uuid"
)

// Problem is the resolver for the problem field.
func (r *testResolver) Problem(ctx context.Context, obj *tirion.Test) (*tirion.Problem, error) {
	if obj == nil {
		return nil, nil
	}

	// TODO: Добавить dataloader
	problem, err := r.tirionHelper.GetProblemByID(ctx, uuid.MustParse(obj.ProblemId))
	if err != nil {
		return nil, err
	}

	return problem, nil
}

// Input is the resolver for the input field.
func (r *testResolver) Input(ctx context.Context, obj *tirion.Test) (string, error) {
	return obj.InputData, nil
}

// Output is the resolver for the output field.
func (r *testResolver) Output(ctx context.Context, obj *tirion.Test) (string, error) {
	return obj.OutputData, nil
}

// Test returns generated.TestResolver implementation.
func (r *Resolver) Test() generated.TestResolver { return &testResolver{r} }

type testResolver struct{ *Resolver }
