// Code generated by clients_gen. DO NOT EDIT.

package config

import (
	"context"
	"fmt"

	"google.golang.org/grpc"

	tirionclientPkg "github.com/CodefriendOrg/daenerys/internal/pb/github.com/CodefriendOrg/tirion/pkg/tirion"
)

type GrpcClientsContainer struct {
	tirionclient tirionclientPkg.TirionClient
}

func NewGrpcClientsContainer(ctx context.Context) (*GrpcClientsContainer, error) {
	s := &GrpcClientsContainer{}
	var serviceUrl string
	var err error
	var conn grpc.ClientConnInterface

	serviceUrl = "codefriend-tirion-hjtvwc:50051"
	conn, err = dialContainerService(ctx, serviceUrl, "3s")
	if err != nil {
		return nil, fmt.Errorf("dialContainerService for service %s failed %w", serviceUrl, err)
	}
	s.tirionclient = tirionclientPkg.NewTirionClient(conn)

	return s, nil
}

func (s *GrpcClientsContainer) GetTirionclient() tirionclientPkg.TirionClient {
	return s.tirionclient
}
