// Code generated by clients_gen. DO NOT EDIT.

package config

import (
	"context"
	"fmt"

	"google.golang.org/grpc"

	daenerysclientPkg "github.com/CodefriendOrg/arya/internal/pb/github.com/CodefriendOrg/daenerys/pkg/daenerys"
	kingsguardclientPkg "github.com/CodefriendOrg/arya/internal/pb/github.com/CodefriendOrg/kingsguard/pkg/kingsguard"
	tirionclientPkg "github.com/CodefriendOrg/arya/internal/pb/github.com/CodefriendOrg/tirion/pkg/tirion"
)

type GrpcClientsContainer struct {
	kingsguardclient kingsguardclientPkg.KingsguardClient
	daenerysclient   daenerysclientPkg.DaenerysClient
	tirionclient     tirionclientPkg.TirionClient
}

func NewGrpcClientsContainer(ctx context.Context) (*GrpcClientsContainer, error) {
	s := &GrpcClientsContainer{}
	var serviceUrl string
	var err error
	var conn grpc.ClientConnInterface

	serviceUrl = "codefriend-kingsguard-zsqd1w:50051"
	conn, err = dialContainerService(ctx, serviceUrl, "3s")
	if err != nil {
		return nil, fmt.Errorf("dialContainerService for service %s failed %w", serviceUrl, err)
	}
	s.kingsguardclient = kingsguardclientPkg.NewKingsguardClient(conn)

	serviceUrl = "codefriend-daenerys-dcma1l:50051"
	conn, err = dialContainerService(ctx, serviceUrl, "3s")
	if err != nil {
		return nil, fmt.Errorf("dialContainerService for service %s failed %w", serviceUrl, err)
	}
	s.daenerysclient = daenerysclientPkg.NewDaenerysClient(conn)

	serviceUrl = "codefriend-tirion-hjtvwc:50051"
	conn, err = dialContainerService(ctx, serviceUrl, "3s")
	if err != nil {
		return nil, fmt.Errorf("dialContainerService for service %s failed %w", serviceUrl, err)
	}
	s.tirionclient = tirionclientPkg.NewTirionClient(conn)

	return s, nil
}

func (s *GrpcClientsContainer) GetKingsguardclient() kingsguardclientPkg.KingsguardClient {
	return s.kingsguardclient
}

func (s *GrpcClientsContainer) GetDaenerysclient() daenerysclientPkg.DaenerysClient {
	return s.daenerysclient
}

func (s *GrpcClientsContainer) GetTirionclient() tirionclientPkg.TirionClient {
	return s.tirionclient
}
