// Code generated by MockGen. DO NOT EDIT.
// Source: internal\pb\github.com\CodefriendOrg\daenerys\pkg\daenerys\daenerys_grpc.pb.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	daenerys "github.com/CodefriendOrg/daenerys/internal/pb/github.com/CodefriendOrg/daenerys/pkg/daenerys"
	grpc "google.golang.org/grpc"
)

// MockDaenerysClient is a mock of DaenerysClient interface.
type MockDaenerysClient struct {
	ctrl     *gomock.Controller
	recorder *MockDaenerysClientMockRecorder
}

// MockDaenerysClientMockRecorder is the mock recorder for MockDaenerysClient.
type MockDaenerysClientMockRecorder struct {
	mock *MockDaenerysClient
}

// NewMockDaenerysClient creates a new mock instance.
func NewMockDaenerysClient(ctrl *gomock.Controller) *MockDaenerysClient {
	mock := &MockDaenerysClient{ctrl: ctrl}
	mock.recorder = &MockDaenerysClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaenerysClient) EXPECT() *MockDaenerysClientMockRecorder {
	return m.recorder
}

// GetSubmission mocks base method.
func (m *MockDaenerysClient) GetSubmission(ctx context.Context, in *daenerys.GetSubmissionRequest, opts ...grpc.CallOption) (*daenerys.Submission, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSubmission", varargs...)
	ret0, _ := ret[0].(*daenerys.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubmission indicates an expected call of GetSubmission.
func (mr *MockDaenerysClientMockRecorder) GetSubmission(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubmission", reflect.TypeOf((*MockDaenerysClient)(nil).GetSubmission), varargs...)
}

// ListSubmissions mocks base method.
func (m *MockDaenerysClient) ListSubmissions(ctx context.Context, in *daenerys.ListSubmissionsRequest, opts ...grpc.CallOption) (*daenerys.ListSubmissionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListSubmissions", varargs...)
	ret0, _ := ret[0].(*daenerys.ListSubmissionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubmissions indicates an expected call of ListSubmissions.
func (mr *MockDaenerysClientMockRecorder) ListSubmissions(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubmissions", reflect.TypeOf((*MockDaenerysClient)(nil).ListSubmissions), varargs...)
}

// SendSubmission mocks base method.
func (m *MockDaenerysClient) SendSubmission(ctx context.Context, in *daenerys.SendSubmissionRequest, opts ...grpc.CallOption) (*daenerys.Submission, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendSubmission", varargs...)
	ret0, _ := ret[0].(*daenerys.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendSubmission indicates an expected call of SendSubmission.
func (mr *MockDaenerysClientMockRecorder) SendSubmission(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSubmission", reflect.TypeOf((*MockDaenerysClient)(nil).SendSubmission), varargs...)
}

// UpdateSubmissionStatus mocks base method.
func (m *MockDaenerysClient) UpdateSubmissionStatus(ctx context.Context, in *daenerys.UpdateSubmissionStatusRequest, opts ...grpc.CallOption) (*daenerys.Submission, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateSubmissionStatus", varargs...)
	ret0, _ := ret[0].(*daenerys.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubmissionStatus indicates an expected call of UpdateSubmissionStatus.
func (mr *MockDaenerysClientMockRecorder) UpdateSubmissionStatus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubmissionStatus", reflect.TypeOf((*MockDaenerysClient)(nil).UpdateSubmissionStatus), varargs...)
}

// MockDaenerysServer is a mock of DaenerysServer interface.
type MockDaenerysServer struct {
	ctrl     *gomock.Controller
	recorder *MockDaenerysServerMockRecorder
}

// MockDaenerysServerMockRecorder is the mock recorder for MockDaenerysServer.
type MockDaenerysServerMockRecorder struct {
	mock *MockDaenerysServer
}

// NewMockDaenerysServer creates a new mock instance.
func NewMockDaenerysServer(ctrl *gomock.Controller) *MockDaenerysServer {
	mock := &MockDaenerysServer{ctrl: ctrl}
	mock.recorder = &MockDaenerysServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaenerysServer) EXPECT() *MockDaenerysServerMockRecorder {
	return m.recorder
}

// GetSubmission mocks base method.
func (m *MockDaenerysServer) GetSubmission(arg0 context.Context, arg1 *daenerys.GetSubmissionRequest) (*daenerys.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubmission", arg0, arg1)
	ret0, _ := ret[0].(*daenerys.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubmission indicates an expected call of GetSubmission.
func (mr *MockDaenerysServerMockRecorder) GetSubmission(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubmission", reflect.TypeOf((*MockDaenerysServer)(nil).GetSubmission), arg0, arg1)
}

// ListSubmissions mocks base method.
func (m *MockDaenerysServer) ListSubmissions(arg0 context.Context, arg1 *daenerys.ListSubmissionsRequest) (*daenerys.ListSubmissionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubmissions", arg0, arg1)
	ret0, _ := ret[0].(*daenerys.ListSubmissionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubmissions indicates an expected call of ListSubmissions.
func (mr *MockDaenerysServerMockRecorder) ListSubmissions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubmissions", reflect.TypeOf((*MockDaenerysServer)(nil).ListSubmissions), arg0, arg1)
}

// SendSubmission mocks base method.
func (m *MockDaenerysServer) SendSubmission(arg0 context.Context, arg1 *daenerys.SendSubmissionRequest) (*daenerys.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendSubmission", arg0, arg1)
	ret0, _ := ret[0].(*daenerys.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendSubmission indicates an expected call of SendSubmission.
func (mr *MockDaenerysServerMockRecorder) SendSubmission(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSubmission", reflect.TypeOf((*MockDaenerysServer)(nil).SendSubmission), arg0, arg1)
}

// UpdateSubmissionStatus mocks base method.
func (m *MockDaenerysServer) UpdateSubmissionStatus(arg0 context.Context, arg1 *daenerys.UpdateSubmissionStatusRequest) (*daenerys.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubmissionStatus", arg0, arg1)
	ret0, _ := ret[0].(*daenerys.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubmissionStatus indicates an expected call of UpdateSubmissionStatus.
func (mr *MockDaenerysServerMockRecorder) UpdateSubmissionStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubmissionStatus", reflect.TypeOf((*MockDaenerysServer)(nil).UpdateSubmissionStatus), arg0, arg1)
}

// mustEmbedUnimplementedDaenerysServer mocks base method.
func (m *MockDaenerysServer) mustEmbedUnimplementedDaenerysServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedDaenerysServer")
}

// mustEmbedUnimplementedDaenerysServer indicates an expected call of mustEmbedUnimplementedDaenerysServer.
func (mr *MockDaenerysServerMockRecorder) mustEmbedUnimplementedDaenerysServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedDaenerysServer", reflect.TypeOf((*MockDaenerysServer)(nil).mustEmbedUnimplementedDaenerysServer))
}

// MockUnsafeDaenerysServer is a mock of UnsafeDaenerysServer interface.
type MockUnsafeDaenerysServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeDaenerysServerMockRecorder
}

// MockUnsafeDaenerysServerMockRecorder is the mock recorder for MockUnsafeDaenerysServer.
type MockUnsafeDaenerysServerMockRecorder struct {
	mock *MockUnsafeDaenerysServer
}

// NewMockUnsafeDaenerysServer creates a new mock instance.
func NewMockUnsafeDaenerysServer(ctrl *gomock.Controller) *MockUnsafeDaenerysServer {
	mock := &MockUnsafeDaenerysServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeDaenerysServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeDaenerysServer) EXPECT() *MockUnsafeDaenerysServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedDaenerysServer mocks base method.
func (m *MockUnsafeDaenerysServer) mustEmbedUnimplementedDaenerysServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedDaenerysServer")
}

// mustEmbedUnimplementedDaenerysServer indicates an expected call of mustEmbedUnimplementedDaenerysServer.
func (mr *MockUnsafeDaenerysServerMockRecorder) mustEmbedUnimplementedDaenerysServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedDaenerysServer", reflect.TypeOf((*MockUnsafeDaenerysServer)(nil).mustEmbedUnimplementedDaenerysServer))
}
