// Code generated by MockGen. DO NOT EDIT.
// Source: internal\pb\github.com\CodefriendOrg\tirion\pkg\tirion\tirion_grpc.pb.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	tirion "github.com/CodefriendOrg/daenerys/internal/pb/github.com/CodefriendOrg/tirion/pkg/tirion"
	grpc "google.golang.org/grpc"
)

// MockTirionClient is a mock of TirionClient interface.
type MockTirionClient struct {
	ctrl     *gomock.Controller
	recorder *MockTirionClientMockRecorder
}

// MockTirionClientMockRecorder is the mock recorder for MockTirionClient.
type MockTirionClientMockRecorder struct {
	mock *MockTirionClient
}

// NewMockTirionClient creates a new mock instance.
func NewMockTirionClient(ctrl *gomock.Controller) *MockTirionClient {
	mock := &MockTirionClient{ctrl: ctrl}
	mock.recorder = &MockTirionClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTirionClient) EXPECT() *MockTirionClientMockRecorder {
	return m.recorder
}

// CreateProblem mocks base method.
func (m *MockTirionClient) CreateProblem(ctx context.Context, in *tirion.CreateProblemRequest, opts ...grpc.CallOption) (*tirion.Problem, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateProblem", varargs...)
	ret0, _ := ret[0].(*tirion.Problem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProblem indicates an expected call of CreateProblem.
func (mr *MockTirionClientMockRecorder) CreateProblem(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProblem", reflect.TypeOf((*MockTirionClient)(nil).CreateProblem), varargs...)
}

// GetProblem mocks base method.
func (m *MockTirionClient) GetProblem(ctx context.Context, in *tirion.GetProblemRequest, opts ...grpc.CallOption) (*tirion.GetProblemResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProblem", varargs...)
	ret0, _ := ret[0].(*tirion.GetProblemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProblem indicates an expected call of GetProblem.
func (mr *MockTirionClientMockRecorder) GetProblem(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProblem", reflect.TypeOf((*MockTirionClient)(nil).GetProblem), varargs...)
}

// ListProblems mocks base method.
func (m *MockTirionClient) ListProblems(ctx context.Context, in *tirion.ListProblemsRequest, opts ...grpc.CallOption) (*tirion.ListProblemsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListProblems", varargs...)
	ret0, _ := ret[0].(*tirion.ListProblemsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProblems indicates an expected call of ListProblems.
func (mr *MockTirionClientMockRecorder) ListProblems(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProblems", reflect.TypeOf((*MockTirionClient)(nil).ListProblems), varargs...)
}

// ListTests mocks base method.
func (m *MockTirionClient) ListTests(ctx context.Context, in *tirion.ListTestsRequest, opts ...grpc.CallOption) (*tirion.ListTestsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTests", varargs...)
	ret0, _ := ret[0].(*tirion.ListTestsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTests indicates an expected call of ListTests.
func (mr *MockTirionClientMockRecorder) ListTests(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTests", reflect.TypeOf((*MockTirionClient)(nil).ListTests), varargs...)
}

// MockTirionServer is a mock of TirionServer interface.
type MockTirionServer struct {
	ctrl     *gomock.Controller
	recorder *MockTirionServerMockRecorder
}

// MockTirionServerMockRecorder is the mock recorder for MockTirionServer.
type MockTirionServerMockRecorder struct {
	mock *MockTirionServer
}

// NewMockTirionServer creates a new mock instance.
func NewMockTirionServer(ctrl *gomock.Controller) *MockTirionServer {
	mock := &MockTirionServer{ctrl: ctrl}
	mock.recorder = &MockTirionServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTirionServer) EXPECT() *MockTirionServerMockRecorder {
	return m.recorder
}

// CreateProblem mocks base method.
func (m *MockTirionServer) CreateProblem(arg0 context.Context, arg1 *tirion.CreateProblemRequest) (*tirion.Problem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProblem", arg0, arg1)
	ret0, _ := ret[0].(*tirion.Problem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProblem indicates an expected call of CreateProblem.
func (mr *MockTirionServerMockRecorder) CreateProblem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProblem", reflect.TypeOf((*MockTirionServer)(nil).CreateProblem), arg0, arg1)
}

// GetProblem mocks base method.
func (m *MockTirionServer) GetProblem(arg0 context.Context, arg1 *tirion.GetProblemRequest) (*tirion.GetProblemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProblem", arg0, arg1)
	ret0, _ := ret[0].(*tirion.GetProblemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProblem indicates an expected call of GetProblem.
func (mr *MockTirionServerMockRecorder) GetProblem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProblem", reflect.TypeOf((*MockTirionServer)(nil).GetProblem), arg0, arg1)
}

// ListProblems mocks base method.
func (m *MockTirionServer) ListProblems(arg0 context.Context, arg1 *tirion.ListProblemsRequest) (*tirion.ListProblemsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProblems", arg0, arg1)
	ret0, _ := ret[0].(*tirion.ListProblemsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProblems indicates an expected call of ListProblems.
func (mr *MockTirionServerMockRecorder) ListProblems(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProblems", reflect.TypeOf((*MockTirionServer)(nil).ListProblems), arg0, arg1)
}

// ListTests mocks base method.
func (m *MockTirionServer) ListTests(arg0 context.Context, arg1 *tirion.ListTestsRequest) (*tirion.ListTestsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTests", arg0, arg1)
	ret0, _ := ret[0].(*tirion.ListTestsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTests indicates an expected call of ListTests.
func (mr *MockTirionServerMockRecorder) ListTests(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTests", reflect.TypeOf((*MockTirionServer)(nil).ListTests), arg0, arg1)
}

// mustEmbedUnimplementedTirionServer mocks base method.
func (m *MockTirionServer) mustEmbedUnimplementedTirionServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedTirionServer")
}

// mustEmbedUnimplementedTirionServer indicates an expected call of mustEmbedUnimplementedTirionServer.
func (mr *MockTirionServerMockRecorder) mustEmbedUnimplementedTirionServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedTirionServer", reflect.TypeOf((*MockTirionServer)(nil).mustEmbedUnimplementedTirionServer))
}

// MockUnsafeTirionServer is a mock of UnsafeTirionServer interface.
type MockUnsafeTirionServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeTirionServerMockRecorder
}

// MockUnsafeTirionServerMockRecorder is the mock recorder for MockUnsafeTirionServer.
type MockUnsafeTirionServerMockRecorder struct {
	mock *MockUnsafeTirionServer
}

// NewMockUnsafeTirionServer creates a new mock instance.
func NewMockUnsafeTirionServer(ctrl *gomock.Controller) *MockUnsafeTirionServer {
	mock := &MockUnsafeTirionServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeTirionServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeTirionServer) EXPECT() *MockUnsafeTirionServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedTirionServer mocks base method.
func (m *MockUnsafeTirionServer) mustEmbedUnimplementedTirionServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedTirionServer")
}

// mustEmbedUnimplementedTirionServer indicates an expected call of mustEmbedUnimplementedTirionServer.
func (mr *MockUnsafeTirionServerMockRecorder) mustEmbedUnimplementedTirionServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedTirionServer", reflect.TypeOf((*MockUnsafeTirionServer)(nil).mustEmbedUnimplementedTirionServer))
}
